# Generated by Django 6.0.3 on 2026-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('std_roll', models.IntegerField()),
                ('std_image', models.ImageField(upload_to='students/')),
                ('std_city', models.CharField(max_length=100)),
            ],
        ),
    ]
